pipeline:
  publish-base:
    image: plugins/docker
    settings:
      dockerfile: ci-base.dockerfile
      username: dawids
      password:
        from_secret: docker_password
      repo: git.dawidsobczak.com/dawids/fern-base
      registry: git.dawidsobczak.com
      tags: latest
#    when:
#      path: "ci-base.dockerfile"

  build:
    image: git.dawidsobczak.com/dawids/fern-base:latest
    pull: true
    commands:
      - cargo build

  test:
    image: git.dawidsobczak.com/dawids/fern-base:latest
    commands:
      - cargo test