[package]
name = "fern"
version = "0.1.0"
edition = "2021"

[lib]
name = "core"
path = "src/lib.rs"

[[bin]]
name = "fern"
path = "src/main.rs"

[dependencies]
tinyrand = { version = "0.5.0", optional = false }
crossbeam-deque = { version = "0.8.3", optional = false }
crossbeam-channel = { version = "0.5.7", optional = false }
crossbeam-skiplist = { version = "0.1", optional = false }
memmap = { version = "0.7.0", optional = false }
hyper = { version = "0.14.26", optional = false }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }

[[bench]]
name = "lexer"
harness = false
