#!/bin/bash

SESSIONNAME="blogger"
tmux has-session -t $SESSIONNAME &> /dev/null

if [ $? != 0 ] 
 then
    tmux new-session -s $SESSIONNAME -n 'code' -d "cd ~/Projects/$SESSIONNAME && bash -e 'nvim'" \;\
         new-window -t $SESSIONNAME -n 'terminal' -d "cd ~/Projects/$SESSIONNAME && bash"
fi

tmux attach -t $SESSIONNAME
